name:          R Style Guide
description:   Best practices for readable, sharable, and verifiable R code
url:           http://jefworks.github.io/R-style-guide/
markdown:      rdiscount
permalink:     pretty